actions: 2
image: not_img
bottom_right_x: None
bottom_right_y: None
top_left_x: None
top_left_y: None
decay: 1.0e-06
env_name: CartPole-v0
eps: 0.1
exploration: greedy
gain: 5
gamma: 0.9
gpu: false
input_shape: !!python/tuple
- 4
- 1
- 4
max_episode_steps: 1000
nstack: 4
path: Policy/
start_from_pretrained: 0
learning_rate: 0.001
Total_Q_Iterations: 50
sample_size: 8000
target_update_iterations: 5
regess_for_epochs: 40